language: python
python:
  - "2.7"

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
- curl -L https://github.com/pololu/pushbutton-arduino/archive/master.tar.gz | tar xz -C /tmp

env:
- BOARD=leonardo
- BOARD=micro
- BOARD=megaatmega2560
- BOARD=due
- BOARD=uno
- BOARD=yun

script:
- set -eo pipefail;
- for e in examples/*; do
    platformio ci --board=$BOARD --lib=. --lib=/tmp/pushbutton-arduino-master $e/*;
  done
